[workspace]
resolver = "2"
members = [
    "qemu",
    "qemu-plugin",
    "qemu-plugin/examples/tiny",
    "qemu-plugin/examples/tracer",
]

[workspace.dependencies]
qemu-plugin-sys = { path = "qemu-plugin-sys" }
qemu-plugin = { path = "qemu-plugin" }
