[workspace]
members = [
    "qemu",
    "binaries/qemu-aarch64",
    "binaries/qemu-alpha",
    "binaries/qemu-arm",
    "binaries/qemu-armeb",
    "binaries/qemu-cris",
    "binaries/qemu-hexagon",
    "binaries/qemu-hppa",
    "binaries/qemu-i386",
    "binaries/qemu-loongarch64",
    "binaries/qemu-m68k",
    "binaries/qemu-microblaze",
    "binaries/qemu-microblazeel",
    "binaries/qemu-mips",
    "binaries/qemu-mips64",
    "binaries/qemu-mips64el",
    "binaries/qemu-mipsel",
    "binaries/qemu-mipsn32",
    "binaries/qemu-mipsn32el",
    "binaries/qemu-nios2",
    "binaries/qemu-or1k",
    "binaries/qemu-ppc",
    "binaries/qemu-ppc64",
    "binaries/qemu-ppc64le",
    "binaries/qemu-riscv32",
    "binaries/qemu-riscv64",
    "binaries/qemu-s390x",
    "binaries/qemu-sh4",
    "binaries/qemu-sh4eb",
    "binaries/qemu-sparc",
    "binaries/qemu-sparc32plus",
    "binaries/qemu-sparc64",
    "binaries/qemu-system-aarch64",
    "binaries/qemu-system-alpha",
    "binaries/qemu-system-arm",
    "binaries/qemu-system-avr",
    "binaries/qemu-system-cris",
    "binaries/qemu-system-hppa",
    "binaries/qemu-system-i386",
    "binaries/qemu-system-loongarch64",
    "binaries/qemu-system-m68k",
    "binaries/qemu-system-microblaze",
    "binaries/qemu-system-microblazeel",
    "binaries/qemu-system-mips",
    "binaries/qemu-system-mips64",
    "binaries/qemu-system-mips64el",
    "binaries/qemu-system-mipsel",
    "binaries/qemu-system-nios2",
    "binaries/qemu-system-or1k",
    "binaries/qemu-system-ppc",
    "binaries/qemu-system-ppc64",
    "binaries/qemu-system-riscv32",
    "binaries/qemu-system-riscv64",
    "binaries/qemu-system-rx",
    "binaries/qemu-system-s390x",
    "binaries/qemu-system-sh4",
    "binaries/qemu-system-sh4eb",
    "binaries/qemu-system-sparc",
    "binaries/qemu-system-sparc64",
    "binaries/qemu-system-tricore",
    "binaries/qemu-system-x86_64",
    "binaries/qemu-system-xtensa",
    "binaries/qemu-system-xtensaeb",
    "binaries/qemu-x86_64",
    "binaries/qemu-xtensa",
    "binaries/qemu-xtensaeb",
]
