[package]
name = "qemu-x86_64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memfd-exec = "0.1.4"
qemu = { version = "0.1.3", features = ["qemu-x86_64"] }
memfd-exec = "0.1.4"
