[package]
name = "qemu-plugin"
authors.workspace = true
categories.workspace = true
description = "High level bindings to the QEMU plugin API"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.75"
once_cell = "1.19.0"
qemu-plugin-sys = { version = "8.2.2-v0", workspace = true }
thiserror = "1.0.51"

[target.'cfg(windows)'.dependencies.windows]
version = "0.52"
features = [
    "Win32_System_WindowsProgramming",
    "Win32_System_LibraryLoader",
    "Win32_Foundation",
]

[target.'cfg(windows)'.dependencies.libc]
version = "0.2.152"

[features]
# Define external symbols with weak definition
unix-weak-link = []
