[package]
name = "qemu-plugin"
authors.workspace = true
categories.workspace = true
description = "High level bindings to the QEMU plugin API"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.75"
once_cell = "1.19.0"
qemu-plugin-sys.workspace = true
thiserror = "1.0.51"
