name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_examples:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Install QEMU User
        run: |
          apt-get -y update && \
          apt-get -y install git curl qemu-user
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/checkout@v4
      - name: Test QEMU Install
        run: |
          qemu-x86_64 --help
      - name: Build
        run: |
          cd plugins/tracer
          cargo build -r
          cargo run -r --bin tracer -- -a /bin/ls -- -lah
