name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install QEMU Build Dependencies
        run: |
          sudo apt-get -y install git libglib2.0-dev libfdt-dev \
            libpixman-1-dev zlib1g-dev ninja-build
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/checkout@v3
      - name: Build and Test Tracer
        run: cargo run -r --bin tracer -- -a /bin/ls -- -lah
