name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_plugins_linux:
    name: Build and Test Plugins (Linux)
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: Install QEMU User
        run: |
          apt-get -y update && \
          apt-get -y install git curl qemu-user build-essential
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/checkout@v4
      - name: Test QEMU Install
        run: |
          qemu-x86_64 --help
      - name: Build and Test Tracer
        run: |
          cd plugins/tracer
          cargo build -r || exit 0
          cargo build -r
          cargo run -r --bin tracer -- -a /bin/ls -- -lah
          cd ../..
      - name: Build and Test Tiny
        run: |
          cd plugins/tiny
          cargo build -r || exit 0
          cargo build -r
          qemu-x86_64 -plugin ../../target/release/libtiny.so /bin/ls -lah
          cd ../..

  test_plugins_windows:
    name: Build and Test Plugins (Windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      # QEMU 8.1.0
      QEMU_URL: "https://qemu.weilnetz.de/w64/2023/qemu-w64-setup-20230822.exe"
      RUSTUP_URL: "https://win.rustup.rs/x86_64"
      UBUNTU_CLOUDIMG_URL: "https://cloud-images.ubuntu.com/releases/22.04/release-20231211/ubuntu-22.04-server-cloudimg-amd64.img"

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc

      - name: Download and Install Rust
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri ${{ env.RUSTUP_URL }} -OutFile rustup-init.exe
          ./rustup-init.exe --default-toolchain nightly --default-host x86_64-pc-windows-gnu -y

      - name: Install QEMU
        shell: msys2 {0}
        run: |
          pacman -Syu --noconfirm
          pacman -Sy mingw-w64-ucrt-x86_64-qemu --noconfirm

      - uses: actions/checkout@v4

      - name: Download Ubuntu Cloud Image
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri ${{ env.UBUNTU_CLOUDIMG_URL }} -OutFile ubuntu.img

      - name: Build and Test Tiny
        run: |
          cd plugins/tiny
          cargo build -r || exit 0
          cargo build -r
          cd ../..
          qemu-system-x86_64.exe -machine type=q35 -m 2G -nographic -drive if=virtio,format=qcow2,file=ubuntu.img -drive if=virtio,format=raw,file=.github/rsrc/seed.img -plugin target/release/libtiny.so
